@if( $data['lang'] == "en")
    <p>When purchasing any of our services, with any form of payment or type of currency, the client will accept the Terms and Conditions described below and agree that the information recorded in the purchase ticket is correct for the desired service.</p>
    <p>As a result of fulfilling our services for Tourist Transportation in the Riviera Maya (trading as <strong>{{ $data['brand'] }}</strong>), we commit to refunding 100% of the payment for the return service to the client in the event that the service has not been fulfilled on time, in the right place and manner due to our responsibility according to what is established in the purchase ticket.</p>
    <p>To verify the status of your service unit, any questions, comments, cancellations, confirmations, or clarifications about your transportation service, you can contact us from <strong>7:00 AM to 11:00 PM</strong> at <strong>{{ $data['phone_MX'] }}</strong>  from Mexico and <strong>{{ $data['phone_US'] }}</strong> from USA or send an email to <strong><a href="mailto:{{ $data['email'] }}">{{ $data['email'] }}</a></strong></p>
    <p>Due to heavy traffic, weather conditions and road accidents, whose responsibility is beyond our operation, "The Company" has a maximum waiting time for the unit to reach the customer of 40 minutes after the time agreed on the purchase ticket. After this waiting period, the customer may request a claim for non-compliance of the service.</p>
    <p>The company is not responsible for refunds related to air transportation, lodging, food, entrance fees to tours, activities and/or archaeological sites, any other damage or interest.</p>
    <p>The company has the option to omit reimbursements and instead offer open credits in case of weather conditions, natural disasters, pandemics, wars, total or partial road closures due to strikes, work stoppages or demonstrations, road blockages due to traffic accidents or natural disasters, port and airport closures, Once "the company" has provided the transportation service, it will be considered accepted and used by the client; therefore, this service will not be refundable for any reason.</p>
    <p>The client whose name appears on the purchase ticket will be the only one authorized to present questions, clarifications, cancellations, or request a refund.</p>
    <p>For any questions and/or clarifications and/or refund requests, the passenger must have and present the original purchase ticket at all times, which must be in good condition, without alterations, and with the folio perfectly legible.</p>
    <p>In all our services, our units have the facility to wait for the client for a period not exceeding 30 minutes at the indicated location on their Ticket. After this waiting time, the unit will withdraw, leaving no right to any refund. Reporting the service as "No show".</p>
    <p>For Hotel pickup service, the passenger must wait in the Hotel Lobby with their Check Out completed for the requested transportation at the confirmed time by the carrier.</p>
    <p>For Home Pickup service, the client must confirm the exact address and GPS location of their service. <strong>They will have up to 24 hours before the scheduled Pick Up time to confirm the location, date, and time.</strong> If the service is not confirmed within that time frame, it will be considered a Type C canceled service without any responsibility for "the company".</p>
    <p>If the "Pick Up service to be confirmed" option is selected when purchasing the service, the client will have up to 24 hours before the scheduled Pick Up time to confirm the location, date, and time. If the service is not confirmed within that time frame, it will be considered a Type C canceled service without any responsibility for "the company". </p>

    <h2>Cancellation types:</h2>
    <p>In situations of cancellation, the alternative of receiving an open-end credit for an indefinite period of time will always be offered.</p>
    <p>In case of rejection of the open credit; partial or total cancellations will proceed as follows.</p>

    @if( $data['brand'] == "gotransfers.us" )
        <p>You can get a full refund by canceling at least 24 hours before the service.</p>
    @else
        <p> <strong>Type A:</strong> Cancellation more than 12 hours before the scheduled service as stated in the ticket will generate a charge of 15% of the value of the contracted service.</p>
        <p><strong>Type B:</strong> Cancellation 12 hours or less prior to scheduled service as stated on the ticket is non-refundable.</p>
    @endif

    <p>In case of applying a refund, the customer will receive his money in the same form in which the payment was made or apply an open credit.</p>
    
    <p>All clarifications, claims or refund requests for purchases made in cash must be requested by phone. The clarification, claim or refund request will be evaluated before being confirmed or rejected and the resolution will be given via email or telephone.</p>
    <p>All clarifications, claims or refund requests for purchases made with payment by card must be requested exclusively through the email <a href="mailto:{{ $data['email'] }}">{{ $data['email'] }}</a> during business hours, Monday to Friday from 9am to 6pm. If sent outside of those hours, the request will be considered on the next business day. The clarification, claim or refund request will be evaluated before being confirmed or rejected and the resolution will be sent by the same means to the email from which it originated.</p>
    <p>In order to request a refund of any form of payment, amount or destination, the customer must present their official identification.</p>
    <p>In the case of a refund to a card, "the company" must receive an image of the official identification by mail to process it.</p>
    <p>Any authorization for a refund to a card starts via email when the request is sent; thereafter, it is necessary for the customer to print, sign and scan the "Refund Authorization Letter" and the image of the customer's identification, with the return being effective via bank transfer from 2 weeks after the reception of the necessary documentation and information.</p>
    <p>To request an invoice, the customer must send the necessary billing information via email and mention at the time of contracting our service that they want an invoice.</p>
    <p>The customer must send the following information: Purchase ID (Located on the Ticket), Federal Taxpayer Registry key, full name of the Physical or Moral Person, place and date of issuance, total amount indicated on the Ticket, type of currency in which the payment was made, form of payment, billing address (city, state, country and postal code), contact phone number. Invoices will be sent within the next 3 business days to the same email it was requested from.</p>
    <p>The company reserves the right to provide the service and/or make any type of refund when the passenger user is in an alcoholic state, altered due to the consumption of harmful substances, or shows moral and/or physical aggression towards any of our customers and/or collaborators and/or facilities and/or work tools.</p>
    <p>The foregoing in accordance with Article 58, second paragraph, of the Federal Consumer Protection Law.</p>
@endif

@if( $data['lang'] == "es")
    <p>Estos son los t&eacute;rminos y condiciones para los servicios de {{ $data['brand'] }} en la Riviera Maya:</p>
    <p>Al comprar cualquiera de nuestros servicios, con cualquier forma de pago o tipo de moneda, el cliente acepta los T&eacute;rminos y Condiciones descritos a continuaci&oacute;n y est&aacute; de acuerdo en que la informaci&oacute;n registrada en el boleto de compra es correcta para el servicio deseado.</p>
    <p>Como resultado de cumplir nuestros servicios de Transporte Tur&iacute;stico en la Riviera Maya (operando como {{ $data['brand'] }}), nos comprometemos a reembolsar el 100% del pago por el servicio de regreso al cliente en caso de que el servicio no se haya cumplido a tiempo, en el lugar y de la manera correcta debido a nuestra responsabilidad seg&uacute;n lo establecido en el boleto de compra.</p>
    <p>Para verificar el estado de su unidad de servicio, cualquier pregunta, comentario, cancelaci&oacute;n, confirmaci&oacute;n o aclaraci&oacute;n sobre su servicio de transporte, puede contactarnos de 7:00 AM to 11:00 PM at <strong>{{ $data['phone_MX'] }}</strong>  desde M&eacute;xico y al  <strong>{{ $data['phone_US'] }}</strong> desde Estados Unidos y Canad&aacute; o enviar un correo electr&oacute;nico a <strong><a href="mailto:{{ $data['email'] }}">{{ $data['email'] }}</a></strong>.</p>
    <p>Debido al tr&aacute;fico intenso, condiciones clim&aacute;ticas y accidentes de carretera, cuya responsabilidad est&aacute; m&aacute;s all&aacute; de nuestra operaci&oacute;n, "La Compa&ntilde;&iacute;a" tiene un tiempo m&aacute;ximo de espera para que la unidad llegue al cliente de 40 minutos despu&eacute;s del horario acordado en el boleto de compra. Despu&eacute;s de este per&iacute;odo de espera, el cliente puede solicitar un reclamo por incumplimiento del servicio.</p>
    <p>La compa&ntilde;&iacute;a no se hace responsable de reembolsos relacionados con transporte a&eacute;reo, hospedaje, alimentos, entradas a tours, actividades y/o zonas arqueol&oacute;gicas, cualquier otro da&ntilde;o o inter&eacute;s</p>
    <p>La compa&ntilde;&iacute;a tiene la opci&oacute;n de omitir reembolsos y ofrecer a cambio cr&eacute;ditos abiertos en afectaciones derivadas de condiciones clim&aacute;ticas, desastres naturales, pandemias, guerras, cierre total o parcial de carreteras por huelgas, paros laborales o manifestaciones, bloqueo de carreteras por accidentes de tr&aacute;fico o desastres naturales, cierre de puertos y aeropuertos, Una vez que "la compa&ntilde;&iacute;a" haya proporcionado el servicio de transporte, se considerar&aacute; aceptado y utilizado por el cliente; por lo tanto, este servicio no ser&aacute; reembolsable por ning&uacute;n motivo.</p>
    <p>El cliente cuyo nombre aparece en el boleto de compra ser&aacute; el &uacute;nico autorizado para presentar preguntas, aclaraciones, cancelaciones o solicitar un reembolso.</p>
    <p>Para cualquier pregunta y/o aclaraci&oacute;n y/o solicitud de reembolso, el pasajero debe tener y presentar el boleto de compra original en todo momento, que debe estar en buen estado, sin alteraciones y con el folio perfectamente legible.</p>
    <p>En todos nuestros servicios, nuestras unidades tienen la facilidad de esperar al cliente por un per&iacute;odo que no exceda los 30 minutos en el lugar indicado en su boleto. Despu&eacute;s de este tiempo de espera, la unidad se retirar&aacute;, sin derecho a reembolso alguno.</p>
    <p>Para el servicio de recogida en el hotel, el pasajero debe esperar en el lobby del hotel con su Check Out completado para el transporte solicitado en el horario confirmado por la compa&ntilde;&iacute;a.</p>
    <p>Para el servicio de recogida en casas vacacionales, el cliente debe confirmar la direcci&oacute;n exacta de su servicio. Tendr&aacute;n hasta 24 horas antes de la hora programada de recogida para confirmar la ubicaci&oacute;n, la fecha y la hora. Si el servicio no se confirma dentro de ese plazo, se considerar&aacute; un servicio cancelado de Tipo C sin responsabilidad alguna para "la compa&ntilde;&iacute;a".</p>
    <p>Si se selecciona la opci&oacute;n "Recogida por confirmar" al comprar el servicio, el cliente tendr&aacute; hasta 24 horas antes de la hora programada de recogida para confirmar la ubicaci&oacute;n, la fecha y la hora. Si el servicio no se confirma dentro de ese plazo, se considerar&aacute; un servicio cancelado de Tipo C sin responsabilidad alguna para "la compa&ntilde;&iacute;a".</p>
    
    <h2><strong>Tipos de cancelaci&oacute;n:</strong></h2>
    <p>En situaciones de cancelación, siempre se brindará la alternativa de recibir un crédito abierto por tiempo indefinido.</p>
    <p>En caso de rechazar el crédito abierto; las cancelaciones parciales o totales procederán de la siguiente manera.</p>

    @if( $data['brand'] == "gotransfers.us" )
        <p>Puedes obtener un reembolso ¡completo! cancelando al menos 24 horas antes del servicio</p>
    @else
        <p><strong>Tipo A</strong>: La cancelación con más de 12 horas antes del servicio programado según lo establecido en el boleto generará un cargo del 15% del valor del servicio contratado.</p>
        <p><strong>Tipo B</strong>: La cancelación con 12 horas o menos antes del servicio programado según lo establecido en el boleto no es reembolsable.</p>
    @endif

    <p>En caso de un NO SHOW, no se aplica ningún reembolso.</p>
    <p>En caso de aplicar un reembolso, el cliente recibirá su dinero en la misma forma en que se realizó el pago o aplicar un crédito abierto.</p>

    <p>El monto depende del motivo de la queja y est&aacute; sujeto a an&aacute;lisis y autorizaci&oacute;n por parte del personal correspondiente.</p>
    <p>Todas las aclaraciones, reclamos o solicitudes de reembolso por compras en efectivo deben solicitarse por tel&eacute;fono. La aclaraci&oacute;n, reclamo o solicitud de reembolso se evaluar&aacute; antes de confirmarse o rechazarse, y la resoluci&oacute;n se dar&aacute; por correo electr&oacute;nico o tel&eacute;fono.</p>
    <p>Todas las aclaraciones, reclamos o solicitudes de reembolso por compras con tarjeta de cr&eacute;dito deben solicitarse exclusivamente a trav&eacute;s del correo electr&oacute;nico <a href="mailto:{{ $data['email'] }}">{{ $data['email'] }}</a> en horario de oficina, de lunes a viernes de 9 a.m. a 6 p.m. Si se env&iacute;an fuera de ese horario, la solicitud se considerar&aacute; para el siguiente d&iacute;a h&aacute;bil. La aclaraci&oacute;n, reclamo o solicitud de reembolso se evaluar&aacute; antes de confirmarse o rechazarse, y la resoluci&oacute;n se enviar&aacute; por el mismo medio al correo del que proviene.</p>
    <p>Para solicitar un reembolso de cualquier forma de pago, monto o destino, el cliente debe presentar su identificaci&oacute;n oficial.</p>
    <p>En caso de un reembolso a una tarjeta, "la compa&ntilde;&iacute;a" debe recibir una imagen de la identificaci&oacute;n oficial por correo para procesarla.</p>
    <p>Cualquier autorizaci&oacute;n para un reembolso a una tarjeta comienza por correo electr&oacute;nico cuando se env&iacute;a la solicitud; despu&eacute;s, es necesario que el cliente imprima, firme y escanee la "Carta de Autorizaci&oacute;n de Reembolso" y la imagen de la identificaci&oacute;n del cliente, con el reembolso efectivo a trav&eacute;s de una transferencia bancaria a partir de 2 semanas despu&eacute;s de recibir la documentaci&oacute;n e informaci&oacute;n necesarias.</p>
    <p>Para solicitar una factura, el cliente debe enviar la informaci&oacute;n de facturaci&oacute;n necesaria por correo electr&oacute;nico y mencionar al momento de contratar nuestro servicio que desea una factura.</p>
    <p>El cliente debe enviar la siguiente informaci&oacute;n: ID de compra (ubicado en el boleto), clave del Registro Federal de Contribuyentes, nombre completo de la Persona F&iacute;sica o Moral, lugar y fecha de emisi&oacute;n, monto total indicado en el boleto, tipo de moneda en que se realiz&oacute; el pago, forma de pago, direcci&oacute;n de facturaci&oacute;n (ciudad, estado, pa&iacute;s y c&oacute;digo postal), n&uacute;mero de tel&eacute;fono de contacto.</p>
    <p>El cliente debe enviar la siguiente informaci&oacute;n: ID de compra (ubicado en el boleto), clave del Registro Federal de Contribuyentes, nombre completo de la Persona F&iacute;sica o Moral, lugar y fecha de emisi&oacute;n, monto total indicado en el boleto, tipo de moneda en que se realiz&oacute; el pago, forma de pago, direcci&oacute;n de facturaci&oacute;n (ciudad, estado, pa&iacute;s y c&oacute;digo postal), n&uacute;mero de tel&eacute;fono de contacto. Las facturas se enviar&aacute;n en los pr&oacute;ximos 3 d&iacute;as h&aacute;biles al mismo correo electr&oacute;nico desde el que se solicit&oacute;.</p>
    <p>La empresa se reserva el derecho de proporcionar el servicio y/o realizar cualquier tipo de reembolso cuando el pasajero se encuentre en estado de embriaguez, alterado debido al consumo de sustancias nocivas o muestre agresi&oacute;n moral y/o f&iacute;sica hacia cualquiera de nuestros clientes, colaboradores, instalaciones o herramientas de trabajo.</p>
    <p>Lo anterior, de acuerdo con el Art&iacute;culo 58, segundo p&aacute;rrafo, de la Ley Federal de Protecci&oacute;n al Consumidor.</p>
@endif